In [216]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [217]:
df=pd.read_csv("novagen_dataset.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9549 entries, 0 to 9548
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    9549 non-null   float64
 1   BMI                    9549 non-null   float64
 2   Blood_Pressure         9549 non-null   float64
 3   Cholesterol            9549 non-null   float64
 4   Glucose_Level          9549 non-null   float64
 5   Heart_Rate             9549 non-null   float64
 6   Sleep_Hours            9549 non-null   float64
 7   Exercise_Hours         9549 non-null   float64
 8   Water_Intake           9549 non-null   float64
 9   Stress_Level           9549 non-null   float64
 10  Target                 9549 non-null   int64
 11  Smoking                9549 non-null   int64
 12  Alcohol                9549 non-null   int64
 13  Diet                   9549 non-null   int64
 14  MentalHealth           9549 non-null   int64
 15  PhysicalActivity       9549 non-null   int64
 16  MedicalHistory         9549 non-null   int64
 17  Allergies              9549 non-null   int64
 18  Diet_Type__Vegan       9549 non-null   bool
 19  Diet_Type__Vegetarian  9549 non-null   bool
 20  Blood_Group_AB         9549 non-null   bool
 21  Blood_Group_B          9549 non-null   bool
 22  Blood_Group_O          9549 non-null   bool
dtypes: bool(5), float64(10), int64(8)
memory usage: 1.4 MB

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,25.660697,130.382658,199.091528,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,1.005864,0.998429,1.003351,1.004713,0.989318
std,24.566473,1.942369,27.878476,1.969234,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,0.815877,0.821844,0.808800,0.813506,0.815699
min,0.000000,19.000000,22.000000,192.000000,93.000000,67.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,24.000000,113.000000,198.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,26.000000,134.000000,199.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,50.000000,27.000000,150.000000,200.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,100.000000,32.000000,225.000000,207.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [218]:
df.tail()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
9544,5.0,22.0,109.0,203.0,98.0,75.0,8.0,1.0,6.0,0.0,...,0,2,2,1,0,True,False,True,False,False
9545,94.0,26.0,144.0,203.0,96.0,72.0,8.0,4.0,2.0,1.0,...,1,0,1,0,2,False,True,False,True,False
9546,10.0,23.0,185.0,198.0,103.0,72.0,4.0,5.0,5.0,6.0,...,1,0,2,0,1,True,False,True,False,False
9547,50.0,29.0,166.0,200.0,100.0,74.0,8.0,2.0,3.0,4.0,...,2,0,0,1,1,True,False,True,False,False
9548,69.0,29.0,178.0,203.0,100.0,75.0,10.0,-0.0,6.0,2.0,...,1,2,1,2,0,False,False,True,False,False

In [219]:
X=df.drop("Target",axis=1)
y=df["Target"]
X.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [220]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
180,13.0,25.0,97.0,197.0,99.0,73.0,7.0,2.0,5.0,3.0,...,1,2,1,0,1,False,False,False,False,False
1115,77.0,26.0,130.0,203.0,97.0,72.0,8.0,2.0,3.0,1.0,...,0,2,1,1,1,False,True,True,False,False
4398,3.0,27.0,149.0,198.0,103.0,73.0,8.0,2.0,4.0,5.0,...,2,0,1,2,1,True,False,True,False,False
8265,1.0,23.0,147.0,198.0,104.0,73.0,3.0,4.0,2.0,9.0,...,2,0,1,1,1,True,False,True,False,False
9469,9.0,24.0,147.0,199.0,98.0,72.0,7.0,0.0,4.0,2.0,...,0,0,2,2,2,False,True,False,False,False

In [221]:
#scalling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

In [222]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train_scaled,y_train)

KNeighborsClassifier(n_neighbors=9)

In [223]:
y_pred=knn.predict(X_test_scaled)
from sklearn.metrics import accuracy_score, classification_report, recall_score
print("recall_score=",recall_score(y_test,y_pred))
print("accuracy_score=",accuracy_score(y_test,y_pred))

recall_score= 0.8871287128712871
accuracy_score= 0.8848167539267016

In [224]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train_scaled,y_train)

LogisticRegression()

In [225]:
y_pred=lr.predict(X_test_scaled)
from sklearn.metrics import accuracy_score, classification_report, recall_score
print("recall_score=",recall_score(y_test,y_pred))
print("accuracy_score=",accuracy_score(y_test,y_pred))

recall_score= 0.8376237623762376
accuracy_score= 0.8225130890052356

In [226]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_scaled,y_train)

GaussianNB()

In [227]:
y_pred=gnb.predict(X_test_scaled)
from sklearn.metrics import accuracy_score, classification_report, recall_score
print("recall_score=",recall_score(y_test,y_pred))
print("accuracy_score=",accuracy_score(y_test,y_pred))

recall_score= 0.80990099009901
accuracy_score= 0.8209424083769633

In [228]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=501,
    oob_score=True,
    max_depth=4,
 random_state=0)
clf.fit(X_train_scaled, y_train)

RandomForestClassifier(max_depth=4, n_estimators=501, oob_score=True,
                       random_state=0)

In [229]:
y_pred=clf.predict(X_test_scaled)
from sklearn.metrics import accuracy_score, classification_report, recall_score
print("recall_score=",recall_score(y_test,y_pred))
print("accuracy_score=",accuracy_score(y_test,y_pred))

recall_score= 0.9099009900990099
accuracy_score= 0.8513089005235602

In [230]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8,
    random_state=42)
gbc.fit(X_train_scaled,y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200,
                           random_state=42, subsample=0.8)

In [231]:
y_pred=gbc.predict(X_test_scaled)
from sklearn.metrics import accuracy_score, classification_report, recall_score
print("recall_score=",recall_score(y_test,y_pred))
print("accuracy_score=",accuracy_score(y_test,y_pred))

recall_score= 0.9247524752475248
accuracy_score= 0.9198952879581151

In [232]:
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(
    estimators=[
        ("lr", LogisticRegression(max_iter=1000, solver="liblinear")),
        ("knn", KNeighborsClassifier(n_neighbors=9)),
        ("rf", RandomForestClassifier(n_estimators=200, random_state=42))
    ],
    voting="soft"
)

voting_clf.fit(X_train_scaled, y_train)

y_pred_vote = voting_clf.predict(X_test_scaled)

print("Voting Classifier Accuracy:", accuracy_score(y_test, y_pred_vote))
print("Voting Classifier Recall:", recall_score(y_test, y_pred_vote))
print(classification_report(y_test, y_pred_vote))

Voting Classifier Accuracy: 0.9130890052356021
Voting Classifier Recall: 0.9217821782178218
              precision    recall  f1-score   support

           0       0.91      0.90      0.91       900
           1       0.91      0.92      0.92      1010

    accuracy                           0.91      1910
   macro avg       0.91      0.91      0.91      1910
weighted avg       0.91      0.91      0.91      1910